name: comp9517
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - jupyter>=1.0.0
  - ipykernel>=6.25.0
  - tqdm>=4.65.0
  - ptflops
  - pip
  - pip:
    - opencv-python>=4.8.0
    - Pillow>=10.0.0